apiVersion: apps/v1
kind: Deployment
metadata:
  name: fizzbuzz-deployment
  labels:
    app: fizzbuzz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fizzbuzz
  template:
    metadata:
      labels:
        app: fizzbuzz
    spec:
      containers:
      - name: fizzbuzz
        image: fias/fizzbuzz:latest
        ports:
        - containerPort: 5000
